language: node_js
node_js:
    - "6"

install: true

before_script:
  - "add-apt-repository ppa:wine/wine-builds"
  - "apt-get update"
  - "apt-get install --install-recommends winehq-devel"
  - "npm install -g gulp"
  - "npm install gulp gulp-concat gulp-minify gulp-uglify gulp-install gulp-clean nw-builder gulp-jslint-simple innosetup-compiler gulp-util gulp-clean-css"

script:
  - "gulp clean"
  - "gulp default"
  - "gulp build"
  - "gulp setup"
