language: node_js
node_js:
    - "6"

install: true

before_script:
  - "npm install -g gulp"
  - "npm install gulp gulp-cssshrink gulp-concat gulp-minify gulp-uglify gulp-install gulp-clean nw-builder gulp-jslint-simple"

script:
  - "gulp clean"
  - "gulp default"
  - "gulp build"
  - "gulp setup"
