language: node_js
node_js:
    - "6"

install: true

before_script:
  - "npm install -g gulp"
  - "npm install gulp gulp-concat gulp-minify gulp-uglify gulp-install gulp-clean nw-builder gulp-jslint-simple innosetup-compiler gulp-util gulp-clean-css"
  - "npm wcjs-prebuilt"
script:
  - "gulp clean"
  - "gulp default"
  - "gulp build-linux"
