version: 0.1.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install -g gulp
  - npm install gulp gulp-concat gulp-minify gulp-uglify gulp-install gulp-clean nw-builder gulp-jslint-simple innosetup-compiler gulp-util gulp-clean-css
  - npm install wcjs-prebuilt
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - gulp clean
  - gulp default
  - gulp build
  - gulp changeIcon
  - gulp setup

test: off

branches:
    only:
        - master
artifacts:
  - path: build\setup\PagalPlayerSetup.exe
    name: PagalPlayer